parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\MailerService:
        arguments:
            $noReplyEmail: '%env(MAILER_NO_REPLY_EMAIL)%'
            $fromName: '%env(MAILER_FROM_NAME)%'

    App\Security\ApiAuthenticator:
        arguments:
            $apiKeyHeader: '%env(API_KEY_HEADER)%'
            $apiKeyValue: '%env(API_KEY_VALUE)%'
